name: Build, test and publish

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch repository
      run: git fetch --prune --unshallow
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
          versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion  # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.10.2
      
    - name: Output values 
      run: |
        mkdir -p ./build
        echo "SemVer: ${{ steps.gitversion.outputs.SemVer }}"
        echo "semver=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_OUTPUT
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
        
    - name: Build ComplicatedPrimitives
      run: dotnet build ./src/ComplicatedPrimitives/ComplicatedPrimitives.csproj --configuration Release --framework net8.0 --output ./build /p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch repository
      run: git fetch --prune
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
          
    - name: Test ComplicatedPrimitives
      run: dotnet test ./src/ComplicatedPrimitives.Tests/ComplicatedPrimitives.Tests.csproj --configuration Release --results-directory ./tests --logger "trx;LogFileName=ComplicatedPrimitives.TestsResults.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: tests
        path: ./tests
      
  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event.release != null && github.event.action == 'published'
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ./build
      
    - name: Select packages to publish 
      run: |
        mkdir -p ./published
        cp ./build/SoterDevelopment.ComplicatedPrimitives.${{ needs.build.outputs.semver }}.nupkg ./published
        ls ./published

    - name: Upload published packages
      uses: actions/upload-artifact@v3
      with:
        name: published
        path: ./published
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.RC127CZJ }}
        nuget-version: '5.x'
      
    - name: Publish ComplicatedPrimitives
      run: nuget push "./published/SoterDevelopment.ComplicatedPrimitives.${{ needs.build.outputs.semver }}.nupkg" -source nuget.org -SkipDuplicate
